version: "3"
services:
  celery:
    build:
      context: ../../
      dockerfile: Dockerfile.python
    container_name: celery
    environment:
      - START_CELERY_WORKER=1
      - DATABASE_URL=postgresql://db_user:password@pg-db:5432/text_and_summary_dev
      - CELERY_BROCKER_REDIS_URL=redis://redis:6379/0
      - CELERY_BACKEND_REDIS_URL=redis://redis:6379/1
      - REDIS_CACHE_URL=redis://redis:6379/2
    links:
      - pg-db
      - redis
    depends_on:
      - redis
      - pg-db
    volumes:
      - ../../project-text-and-summary/app:/app/app
      - ../../project-text-and-summary/run.sh:/app/run.sh
      - ../../project-text-and-summary/file_1.log:/app/file_1.log
