version: "3"
services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile.python
    container_name: web
    environment:
      - DATABASE_URL=postgresql://db_user:password@pg-db:5432/text_and_summary_dev
      - CELERY_BROCKER_REDIS_URL=redis://redis:6379/0
      - CELERY_BACKEND_REDIS_URL=redis://redis:6379/1
      - REDIS_CACHE_URL=redis://redis:6379/2
    links:
      - pg-db
      - redis
    depends_on:
      - pg-db
      - redis
    # ports:
    #   - "8001:8001"
    volumes:
      - ../../project-text-and-summary/app:/app/app
      - ../../project-text-and-summary/start_db_session.py:/app/start_db_session.py
      - ../../project-text-and-summary/run.sh:/app/run.sh
      - ../../project-text-and-summary/prestart.sh:/app/prestart.sh
      - ../../project-text-and-summary/alembic:/app/alembic
      - ../../project-text-and-summary/alembic.ini:/app/alembic.ini
      - ../../project-text-and-summary/file_1.log:/app/file_1.log
